import numpy as np
print("*************************************************")
print("SJC22MCA-2035 : KISHOR VINOD")
print("MCA 2022-24")
print("*************************************************")
one_dim_array = np.arange(10)
print("a) First 4 elements:")
print(one_dim_array[:4])
print("\nb) Last 6 elements:")
print(one_dim_array[-6:])
print("\nc) Elements from index 2 to 7:")
print(one_dim_array[2:8])
